### ISSUE TITLE
Suggestion: Add AppVeyor test suite to check for Windows support

### ISSUE THREAD

**Issue by swernerx** [robertklep/node-metrohash#8]
I am the author of [asset hash](https://www.npmjs.com/package/asset-hash) where I chose metrohash as the default hashing algorithm. Right now I experience some issues in my package as it does not seem to correctly compile on [appveyor](https://www.appveyor.com). This seems to be related to Metrohash. This is the output I am currently seeing: 

```
..\src\metrohash128crc.cpp(55): error C3861: '_mm_crc32_u64': identifier not found [C:\projects\rollup-plugin-rebase\node_modules\metrohash\build\metrohash.vcxproj]
...
```

Full log output: https://ci.appveyor.com/project/swernerx/rollup-plugin-rebase/build/136/job/rw5qlf48amcmb9s9

Do have any hint of fixing this? Would it be feasible for you to add appveyor testing? 

A good initial `appveyor.yml` could be this one:

```
# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 8
    - nodejs_version: 10

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm test

cache:
  # global npm cache
  - '%APPDATA%\npm-cache'
```
